# Generated by Django 5.0.7 on 2024-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingid', models.IntegerField()),
                ('housingid', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('building_name', models.CharField(max_length=100)),
                ('building_address', models.TextField()),
                ('building_manager_phsid', models.IntegerField(blank=True, null=True)),
                ('ampid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractid', models.IntegerField()),
                ('contract_effectivedate', models.DateTimeField()),
                ('contract_type', models.CharField(max_length=100)),
                ('contract_address', models.TextField()),
                ('tenantid', models.CharField(max_length=20)),
                ('contract_status', models.CharField(max_length=100)),
                ('contract_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contract_process_status', models.CharField(max_length=100)),
                ('contract_onbase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantid', models.CharField(max_length=20)),
                ('resident_fname', models.CharField(max_length=100)),
                ('resident_lname', models.CharField(max_length=100)),
                ('resident_program', models.CharField(max_length=100)),
                ('last_effective_action', models.IntegerField()),
                ('last_effective_date', models.DateTimeField()),
                ('resident_phonenumber', models.CharField(max_length=15)),
                ('resident_email', models.EmailField(max_length=254)),
                ('resident_address', models.TextField()),
                ('resident_status', models.CharField(max_length=20)),
                ('unitid', models.CharField(max_length=20)),
                ('resident_amp', models.IntegerField()),
            ],
        ),
    ]
