# Generated by Django 5.0.7 on 2024-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_effective_date',
            field=models.DateField(),
        ),
    ]
