# Generated by Django 5.0.7 on 2024-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents_app', '0003_alter_resident_last_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='last_effective_date',
            field=models.CharField(max_length=100),
        ),
    ]
