# Generated by Django 5.0.7 on 2024-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents_app', '0004_alter_resident_last_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingid', models.IntegerField()),
                ('housingid', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('building_name', models.CharField(max_length=100)),
                ('building_address', models.TextField()),
                ('building_manager_phsid', models.IntegerField(blank=True, null=True)),
                ('ampid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractid', models.IntegerField()),
                ('contract_effectivedate', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('contract_address', models.TextField()),
                ('tenantid', models.CharField(max_length=20)),
                ('contract_status', models.CharField(max_length=100)),
                ('contract_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contract_email', models.EmailField(max_length=254)),
                ('contract_amp', models.IntegerField(blank=True, null=True)),
                ('contract_last_recert', models.CharField(max_length=100)),
                ('contract_packet_sent', models.CharField(max_length=100)),
                ('contract_packet_received', models.CharField(max_length=100)),
                ('contract_rent_del_letter_sent', models.CharField(max_length=100)),
                ('contract_unit', models.IntegerField()),
                ('contract_building', models.IntegerField()),
                ('contract_program', models.CharField(max_length=100)),
                ('contract_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_process_status', models.CharField(max_length=100)),
            ],
        ),
    ]
