# Generated by Django 5.0.7 on 2024-07-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents_app', '0005_building_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_rent_del_letter_sent',
            new_name='contract_rent_det_letter_sent',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_manager_phsid',
        ),
    ]
